# Puerto en el que correrá el contenedor de Struts (coincide con el Docker Compose)
server.port=8084

# Nombre del microservicio
spring.application.name=micro-report-struts

# URL del API Gateway dentro de la red de Docker (reemplaza localhost)
gateway.api.url=http://apiGetaway:8082

# URL de Eureka para el registro (si tu versión de Struts incluye el cliente de Spring Cloud)
eureka.client.serviceUrl.defaultZone=http://eurekaService:8081/eureka/
eureka.instance.preferIpAddress=false
eureka.instance.hostname=micro-report-struts
