services:
  eurekaservice:
    build: eurekaService/
    image: eurekaservice:latest
    ports:
      - "8081:8081"
    networks:
      observabilitysandbox:
        aliases:
          - eurekaService
          - eurekaservice
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8081 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  micro-oauth:
    build: micro-oauth/
    image: micro-oauth:latest
    ports:
      - "9191:9191"
    networks:
      - observabilitysandbox
    depends_on:
      eurekaservice:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9191 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  micro-api-quarkus:
    build: micro-api-quarkus/
    image: micro-api-quarkus:latest
    ports:
      - "8085:8085"
    networks:
      - observabilitysandbox
    depends_on:
      eurekaservice:
        condition: service_healthy

  micro-core-spring-boot:
    build: micro-core-spring-boot/
    image: micro-core-spring-boot:latest
    # Cambiado a expose para protegerlo del exterior
    expose:
      - "8083"
    networks:
      - observabilitysandbox
    depends_on:
      eurekaservice:
        condition: service_healthy

  micro-notification-node:
    build: micro-notification-node/
    image: micro-notification-node:latest
    container_name: micro-notification-node
    # Cambiado a expose para que Postman no se salte el Gateway
    expose:
      - "3000"
    networks:
      - observabilitysandbox

  apigateway:
    build: apiGateway/
    image: apigateway:latest
    ports:
      - "8082:8082" # Única puerta de entrada pública a los microservicios
    networks:
      - observabilitysandbox
    depends_on:
      eurekaservice:
        condition: service_healthy
      micro-oauth:
        condition: service_healthy
      micro-core-spring-boot:
        condition: service_started
      micro-api-quarkus:
        condition: service_started
      micro-notification-node:
        condition: service_started

  micro-report-struts:
    build: micro-report-struts/
    image: micro-report-struts:latest
    container_name: micro-report-struts
    ports:
      - "8084:8080"
    networks:
      - observabilitysandbox
    depends_on:
      apigateway:
        condition: service_started

  micro-analytics-python:
    build: micro-analytics-python/
    image: micro-analytics-python:latest
    container_name: micro-analytics-python
    ports:
      - "8000:8000"
    networks:
      - observabilitysandbox
    depends_on:
      apigateway:
        condition: service_started

networks:
  observabilitysandbox:
    external: true
