drop table CRUD;

CREATE TABLE CRUD
(
    ID        NUMBER(8,0) NOT NULL,
    NAME      VARCHAR(50) NOT NULL,
    CONSTRAINT SCHEDULER_JOB_INFO_PK PRIMARY KEY (ID)
);

drop SEQUENCE SEQ_ID_CRUD;
CREATE SEQUENCE SEQ_ID_CRUD START WITH 1 INCREMENT BY 1;

INSERT INTO CRUD (ID,NAME,YEAR,DIRECTOR,COVER) VALUES(SEQ_ID_CRUD.nextval, 'CRUD1');
INSERT INTO CRUD (ID,NAME,YEAR,DIRECTOR,COVER) VALUES(SEQ_ID_CRUD.nextval, 'CRUD2);
INSERT INTO CRUD (ID,NAME,YEAR,DIRECTOR,COVER) VALUES(SEQ_ID_CRUD.nextval, 'CRUD3');

COMMIT;