# Nombre de la aplicación
quarkus.application.name=micro-api-quarkus
  
quarkus.http.port=8085
quarkus.http.host=0.0.0.0
  
  # Context Path idéntico al mapeo del Gateway
quarkus.resteasy.path=/api-quarkus
  
  # Configuración del cliente de Eureka
quarkus.eureka.instance.hostname=micro-api-quarkus
quarkus.eureka.client.register-with-eureka=true
quarkus.eureka.client.service-url.defaultZone=http://eurekaService:8081/eureka/
  
  # Cliente Rest hacia el Gateway
quarkus.rest-client.gateway-api.url=http://apigateway:8082
