quarkus:
  application:
    name: micro-api-quarkus

  http:
    port: 8085
    host: 0.0.0.0

  resteasy:
    path: /api-quarkus

  eureka:
    instance:
      hostname: micro-api-quarkus
    client:
      register-with-eureka: true
      service-url:
        defaultZone: http://eurekaService:8081/eureka/

  rest-client:
    gateway-api:
      url: http://apiGetaway:8082
