quarkus:
  application:
    name: micro-api-quarkus

  http:
    port: 8085

  resteasy:
    path: /api-quarkus

  # 1. Configuración nativa del cliente de Eureka para Quarkus 3.x
  eureka:
    instance:
      hostname: micro-api-quarkus
    client:
      register-with-eureka: true
      service-url:
        defaultZone: http://eurekaService:8081/eureka/

  # 2. Vinculación de la interfaz CoreCrudsClient
  # Apunta al nombre del contenedor del API Gateway (apiGetaway) en su puerto Docker
  rest-client:
    gateway-api:
      url: http://apiGetaway:8082
