server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: micro-oauth-route
          uri: lb://micro-oauth
          predicates:
            - Path=/auth-api/**

        - id: micro-core-route
          uri: http://micro-core-spring-boot:8083
          predicates:
            - Path=/core-api/**

        - id: micro-quarkus-route
          uri: http://micro-api-quarkus:8085
          predicates:
            - Path=/api-quarkus/**

        - id: micro-struts-route
          uri: http://micro-report-struts:8084
          predicates:
            - Path=/reports/**
          filters:
            - 'RewritePath=/reports/(?<segment>.*), /${segment}'

eureka:
  instance:
    prefer-ip-address: false
    hostname: apiGetaway
    appname: API-GATEWAY
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaservice:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health

security:
  oauth2:
    resource:
      jwt:
        key-value: "mi-clave-secreta-de-laboratorio"