server:
  port: 9191
  servlet:
    context-path: /auth-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: -*
        exclude: env,beans