server:
  port: 9191
  servlet:
    context-path: /auth-api

spring:
  application:
    name: micro-oauth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaservice:8081/eureka/
  instance:
    prefer-ip-address: false
    hostname: micro-oauth
    appname: MICRO-OAUTH

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

security:
  oauth2:
    resource:
      jwt:
        key-value: "mi-clave-secreta-de-laboratorio"